# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: techverito
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ama

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MessageTable, Arn]
  stackName: masterclass
  region: ap-south-1

functions:
  api:
    memorySize: 128
    handler: handler.handler
    events:
      - httpApi:
          path: /messages
          method: post
      - httpApi:
          path: /messages
          method: get
plugins:
  - serverless-offline

resources:
  Resources:
    MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: topic
            AttributeType: S
          - AttributeName: ts
            AttributeType: N
        KeySchema:
          - AttributeName: topic
            KeyType: HASH
          - AttributeName: ts
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: messages
